### ISSUE TITLE
Dolphin fails to build

### ISSUE THREAD

**Issue by TrazhCant** [V0rt3x667/ArchyPie-Setup#45] opened 2023-12-06 07:18 UTC
EndeavourOS fully updated, GNOME + WAYLAND

log:

```
[342/1126] Building CXX object Source/Core/Common/CMakeFiles/common.dir/GL/GLExtensions/GLExtensions.cpp.o
[343/1126] Building CXX object Externals/implot/CMakeFiles/implot.dir/implot/implot_items.cpp.o
ninja: build stopped: subcommand failed.
Could not successfully build dolphin - Dolphin: Nintendo Gamecube & Wii Emulator (/home/nutzhell/ArchyPie-Setup/tmp/build/dolphin/build/Binaries/dolphin-emu not found).
/home/nutzhell/ArchyPie-Setup

Log Ended At: Tue Dec  5 11:16:40 PM PST 2023
Total Running Time: 0 hours, 2 mins, 26 secs
```

**Comment by TrazhCant** [comment] 2023-12-06 07:24
To further clarify, the above error log is for the standalone Dolphin.  Here is the log for attempting to build lr-dolphin:

```
[239/797] Building CXX object Externals/glslang/CMakeFiles/glslang.dir/SPIRV/GlslangToSpv.cpp.o
ninja: build stopped: subcommand failed.
Could not successfully build lr-dolphin - Nintendo Gamecube & Wii Libretro Core (/home/nutzhell/ArchyPie-Setup/tmp/build/lr-dolphin/build/dolphin_libretro.so not found).
/home/nutzhell/ArchyPie-Setup

Log Ended At: Tue Dec  5 11:22:20 PM PST 2023
Total Running Time: 0 hours, 1 mins, 47 secs
```

**Comment by V0rt3x667** [comment] 2023-12-07 12:17
I have fixed the issues with both standalone and Libretro Dolphin. Standalone Dolphin has to be built from the same commit used by Arch Linux for their dolphin-emu package. The dolphin devs expect a version of enet that can only be built from git so the Arch Linux enet package no longer works with the latest Dolphin commit available.

**Comment by V0rt3x667** [comment] 2023-12-07 12:19
https://github.com/dolphin-emu/dolphin/pull/12343

**Comment by V0rt3x667** [comment] 2023-12-16 19:56
Closing as the issue is fixed.

**Closed as completed by V0rt3x667** 2023-12-16 19:56 UTC
Labels: bug
